files:
  - source: src/main/resources/default/language/gui/*.yml
    translation: /**/src/main/resources/default/translation/%language%/gui/%file_name%.%file_extension%
  - source: src/main/resources/default/language/*.yml
    translation: /**/src/main/resources/default/translation/%language%/%file_name%.%file_extension%
